[project]
name = "pycraft"
version = "0.1.0"
description = "A fluent Python code generation toolkit."
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
